# Generated by Django 4.2 on 2023-04-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="distance",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="trip",
            name="flight_number",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="trip",
            name="lat",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="trip",
            name="long",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="trip",
            name="type",
            field=models.CharField(default="flight"),
        ),
    ]
